import { League_Spartan } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/theme-provider';
import Provider from '@/components/provider';


const spartan = League_Spartan({ subsets: ['latin'], weight: ['700', '500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={`${spartan.className} antialiased`}>
        <ThemeProvider>
          <Provider>
            {props.children}
            {props.modal}
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
